### ISSUE TITLE
Great optimization of the site

### ISSUE THREAD

**Issue by DanKGooGLy** [GermanBread/germanbread.github.io#1]
![image](https://user-images.githubusercontent.com/34890978/114288869-01e0e600-9a41-11eb-8da9-f4cac5f82c2e.png)
I stumbled across your website, and decided to run a lighthouse benchmark on it, and here are the results.
Here's what I think you should do to the website.
* Serve pictures as the `.webp` or an optimized `.jpeg` format.
* The HTML files don't have the `<meta name="viewport">` tag.
* Just rename about.html to index.html. The redirect is unneeded and slows the website down.
* Your images don't have the `alt` tag.
* Let the fonts use some kind of legible size rather than the current size.
* Use `<html lang=en>` rather than just `<html>` for accessibility.
* Add a meta description to the site.
* Always let the image be 48 pixels or more, if you need it to appear smaller just change the padding.

**Comment by GermanBread** [comment]
> The HTML files don't have the `<meta name="viewport">` tag.

Fixed

> Just rename `about.html` to `index.html`

Done

> Your images don't have the alt tag.

Fixed

> Use `<html lang=en>` rather than just `<html>` for accessibility.

Done

> Add a meta description to the site.

Done

### I will look into getting the rest fixed

## Tysm for your feedback.

*I will push the changes in a minute or two*

**Comment by DanKGooGLy** [comment]
It's looking pretty good. Just so you know, the test I performed was a lighthouse benchmark, and you test the site yourself at [web.dev](https://web.dev/measure).

**Comment by GermanBread** [comment]
Oh okay. Thanks for telling me this.
